version: '3.8'
services:
    db:
        image: postgres:16-bookworm
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
            POSTGRES_DB: devdb
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    redis:
        image: redis:7-bookworm
        ports:
            - '6379:6379'
volumes:
    db_data:
