CREATE TYPE "login_type" AS ENUM (
  'regular',
  'sso'
);

CREATE TYPE "privilege_type" AS ENUM (
  'consumer',
  'store_manager'
);

CREATE TYPE "payment_type" AS ENUM (
  'cash',
  'credit_card',
  'monthly'
);

CREATE TYPE "order_state" AS ENUM (
  'unpaid',
  'paid',
  'aborted'
);

CREATE TABLE "store_tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text NOT NULL
);

CREATE TABLE "store_tag_association" (
  "store_id" integer NOT NULL,
  "tag_id" integer NOT NULL
);

CREATE TABLE "store_data" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "owner_id" integer NOT NULL
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "login_type" login_type NOT NULL
);

CREATE TABLE "user_privilege" (
  "user_id" integer NOT NULL,
  "privilege" privilege_type NOT NULL
);

CREATE TABLE "user_data" (
  "login_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" text NOT NULL,
  "password" text NOT NULL
);

CREATE TABLE "meal_tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text NOT NULL
);

CREATE TABLE "meal_tag_association" (
  "meal_id" integer NOT NULL,
  "tag_id" integer NOT NULL
);

CREATE TABLE "meals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "price" integer NOT NULL,
  "picture" text,
  "category" text NOT NULL,
  "is_available" boolean NOT NULL DEFAULT false,
  "store" integer NOT NULL,
  "customizations" json
);

CREATE TABLE "order_detail" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "meal" integer NOT NULL,
  "number" integer NOT NULL,
  "notes" text NOT NULL
);

CREATE TABLE "order_detail_association" (
  "order_id" integer NOT NULL,
  "order_detail_id" integer NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user" integer NOT NULL,
  "notes" text NOT NULL,
  "payment_type" payment_type NOT NULL,
  "state" order_state NOT NULL,
  "delivery_method" text NOT NULL,
  "created_at" time NOT NULL
);

CREATE UNIQUE INDEX ON "store_tag_association" ("store_id", "tag_id");

CREATE UNIQUE INDEX ON "user_privilege" ("user_id", "privilege");

CREATE UNIQUE INDEX ON "meal_tag_association" ("meal_id", "tag_id");

CREATE UNIQUE INDEX ON "order_detail_association" ("order_id", "order_detail_id");

COMMENT ON COLUMN "store_tags"."name" IS 'TAG 名稱';

COMMENT ON COLUMN "store_data"."name" IS '店家名';

COMMENT ON COLUMN "store_data"."description" IS '店家描述';

COMMENT ON COLUMN "user"."name" IS '姓名';

COMMENT ON COLUMN "user"."login_type" IS 'Regular/SSO';

COMMENT ON COLUMN "user_data"."username" IS '帳號';

COMMENT ON COLUMN "user_data"."password" IS '密碼 hash';

COMMENT ON COLUMN "meal_tags"."name" IS 'TAG 名稱';

COMMENT ON COLUMN "meals"."name" IS '餐點名';

COMMENT ON COLUMN "meals"."description" IS '餐點描述';

COMMENT ON COLUMN "meals"."price" IS '價格';

COMMENT ON COLUMN "meals"."picture" IS 'Image URL';

COMMENT ON COLUMN "meals"."category" IS '餐點類別';

COMMENT ON COLUMN "meals"."customizations" IS '用 json 表示的餐點自訂';

COMMENT ON COLUMN "order_detail"."number" IS '餐點數';

COMMENT ON COLUMN "order_detail"."notes" IS '備註';

COMMENT ON COLUMN "order"."notes" IS '備註';

COMMENT ON COLUMN "order"."delivery_method" IS '領餐方式';

ALTER TABLE "store_tag_association" ADD FOREIGN KEY ("store_id") REFERENCES "store_data" ("id");

ALTER TABLE "store_tag_association" ADD FOREIGN KEY ("tag_id") REFERENCES "store_tags" ("id");

ALTER TABLE "store_data" ADD FOREIGN KEY ("owner_id") REFERENCES "user" ("id");

ALTER TABLE "user_privilege" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_data" ADD FOREIGN KEY ("login_id") REFERENCES "user" ("id");

ALTER TABLE "meal_tag_association" ADD FOREIGN KEY ("meal_id") REFERENCES "meals" ("id");

ALTER TABLE "meal_tag_association" ADD FOREIGN KEY ("tag_id") REFERENCES "meal_tags" ("id");

ALTER TABLE "meals" ADD FOREIGN KEY ("store") REFERENCES "store_data" ("id");

ALTER TABLE "order_detail" ADD FOREIGN KEY ("meal") REFERENCES "meals" ("id");

ALTER TABLE "order_detail_association" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "order_detail_association" ADD FOREIGN KEY ("order_detail_id") REFERENCES "order_detail" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("user") REFERENCES "user" ("id");
